SELECT VILAGES.GID, JAMEYAT, VILAGES.GEOM
FROM VILAGES INNER JOIN SOIL ON ST_INTERSECTS(ST_TRANSFORM(ST_SETSRID(VILAGES.GEOM, 4326), 4326), SOIL.GEOM)
WHERE SOIL.SOIL='IVS' OR SOIL.SOIL='IIS'
ORDER BY JAMEYAT DESC
